### ISSUE TITLE
JWT error

### ISSUE THREAD

**Issue by mischnic** [mischnic/python-ci#32]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./python-ci.py", line 268, in do_GET
    data = jwt.decode(token, JWT_SECRET)
  File "/usr/local/lib/python2.7/dist-packages/jwt/api_jwt.py", line 78, in decode
    jwt, key=key, algorithms=algorithms, options=options, **kwargs
  File "/usr/local/lib/python2.7/dist-packages/jwt/api_jws.py", line 140, in decode
    key, algorithms)
  File "/usr/local/lib/python2.7/dist-packages/jwt/api_jws.py", line 207, in _verify_signature
    raise DecodeError('Signature verification failed')
DecodeError: Signature verification failed
```

**Comment by mischnic** [comment]
doesn't happen anymore?
